name: Build and Publish Images

on:
  schedule:
    - cron:  '0 0 * * 3' # build and publish images every Wednesday
  push:
    branches: 
      - main

jobs:
  publish-base-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.1.0
      if: github.event_name == 'push'
      id: filter
      with:
        filters: '.github/filters.yml'
    - name: Docker login
      if: ${{ github.event_name == 'schedule' || steps.filter.outputs.base_image == 'true' }}
      run: echo "$DOCKER_TOKEN" | docker login --username=$DOCKER_USER --password-stdin
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and publish android-sdk-base.Dockerfile
      if: ${{ github.event_name == 'schedule' || steps.filter.outputs.base_image == 'true' }}
      run: sh publish_android_sdk_base_image.sh

  publish-sdk-image:
    needs: publish-base-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.1.0
      if: github.event_name == 'push'
      id: filter
      with:
        filters: '.github/filters.yml'
    - name: Docker login
      if: ${{ github.event_name == 'schedule' || steps.filter.outputs.base_image == 'true' || steps.filter.outputs.sdk_images == 'true' }}
      run: echo "$DOCKER_TOKEN" | docker login --username=$DOCKER_USER --password-stdin
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and publish android-sdk-${{ matrix.api-level }}.Dockerfile
      if: ${{ github.event_name == 'schedule' || steps.filter.outputs.base_image == 'true' || steps.filter.outputs.sdk_images == 'true' }}
      run: sh publish_android_sdk_image.sh ${{ matrix.api-level }}

  publish-emulator-image:
    needs: publish-sdk-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.1.0
      if: github.event_name == 'push'
      id: filter
      with:
        filters: '.github/filters.yml'
    - name: Docker login
      if: ${{ github.event_name == 'schedule' || steps.filter.outputs.base_image == 'true' || steps.filter.outputs.sdk_images == 'true' || steps.filter.outputs.emulator_images == 'true' }}
      run: echo "$DOCKER_TOKEN" | docker login --username=$DOCKER_USER --password-stdin
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and publish android-emulator-${{ matrix.api-level }}.Dockerfile
      if: ${{ github.event_name == 'schedule' || steps.filter.outputs.base_image == 'true' || steps.filter.outputs.sdk_images == 'true' || steps.filter.outputs.emulator_images == 'true' }}
      run: sh publish_android_emulator_image.sh ${{ matrix.api-level }}
