name: Build and Publish Android Emulator Images

on:
  schedule:
    - cron:  '0 0 * * 3' # build and publish emulator images every Wednesday
  push:
    branches: 
      - master
    paths-ignore:
      - README.md

jobs:
  publish-emulator-image:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [21, 22, 23, 24, 25, 26, 27, 28, 29]

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo "$DOCKER_TOKEN" | docker login --username=$DOCKER_USER --password-stdin
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and publish android-emulator-${{ matrix.api-level }}.Dockerfile
      run: sh publish_android_emulator_image.sh ${{ matrix.api-level }}
